### ISSUE TITLE
How do you pass a dictionary to _AUTHORIZE_PARAMS

### ISSUE THREAD

**Issue by watdev2018** [authlib/loginpass#76]
Consider https://github.com/authlib/loginpass/blob/master/loginpass/_fastapi.py#L81

I'm trying to generate a refresh token for Google and it appears I need to set `access_type: offline` in the authorization url. To be honest, it feels like its black magic to get the refresh token.

Anyways, I don't know how to set a dictionary to the `GOOGLE_AUTHORIZE_PARAMS` when this value is coming from the config, which is an environment variable.

@zaghaghi Have you tried using your PR to generate a refresh token? Any help here would be much appreciated. Thanks!

**Comment by watdev2018** [comment]
Found a workaround,

```
from loginpass import create_fastapi_routes, Twitter, Spotify, Google

Google.OAUTH_CONFIG['client_kwargs'] = {
    'scope': 'https://www.googleapis.com/auth/fitness.activity.read https://www.googleapis.com/auth/userinfo.email openid'
}

backends = [Twitter,Spotify,Google]

config.environ['GOOGLE_AUTHORIZE_PARAMS'] = {'access_type': 'offline'}
oauth = OAuth(config)
```

**Comment by hashcutdev** [comment]
I couldn't get your method to work, because environment variables need to be strings. But Starlette's Config module doesn't interpret dictionaries, so passing "{'access_type': 'offline'}" just leaves it as a string, which causes an error.

But I found a cleaner way. Just add:

`
Google.OAUTH_CONFIG['authorize_params'] = {"access_type": "offline"}
`
You can add any other parameters in the dict as well, and it works like a charm :-)
